---
apiVersion: v1
kind: Service
metadata:
  name: webfrontend
  # annotations:
  #   cloud.google.com/neg: '{"exposed_ports": {"8080":{}}}'
spec:
  type: ClusterIP
  # type: LoadBalancer
  selector:
    app: webfrontend
  ports:
  - name: http
    port: 60000
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
